### ISSUE TITLE
招聘网站练习 @job.save 执行失败

### ISSUE THREAD

**Issue by shaojunda** [quanzhanying/fullstack-course#1]
在执行 JobsController 中的 create 方法时如果不加入 `@job.user = current_user` 保存时会失败，但是不会报错，执行 `puts @job.errors.messages` 后输出 `{:user=>["must exist"]}` 。请问为什么 user 是必须的？

**Comment by niclin** [comment]
因為在後來的migration有新增user欄位

我去你的github看代碼

這段
https://github.com/shaojunda/job-listing/blob/step2/db/migrate/20160726044612_add_user_idto_jobs.rb

以邏輯來說，必須知道job是由何者張貼，所以必須要加入current_user

**Comment by shaojunda** [comment]
@niclin 新增的字段都是必须要加的吗？可以设置为不是必须加吗？
