### ISSUE TITLE
如何传递普通的参数到后台

### ISSUE THREAD

**Issue by shaojunda** [quanzhanying/fullstack-course#11]
如何传递非 Model 字段的参数到后台。

**Comment by nfreeness** [comment]
google  text_field_tag text_area_tag

**Comment by shaojunda** [comment]
1. 使用 `text_field_tag` 可以在页面上生成一个输入框，比如在页面输入 `<%= text_field_tag('name', nil, :placeholder => "haha") %>` 就会生成一个 `<input type="text" name="name" id="name" placeholder="haha">` 在 controller 中可以使用 `name = params[:name]` 来接收这个变量，详细文档请点击 -> [详细文档](http://apidock.com/rails/ActionView/Helpers/FormTagHelper/text_field_tag)
   注意: 如果要使用 :placeholder 等可选参数，`text_field_tag` 的第二个参数必须要输入，默认可以设置为 `nil`。
2. 使用 `text_area_tag` 可以在页面生成一个文本框，比如在页面输入 `<%= text_area_tag('article', nil) %>` 就会生成一个 `<textarea name="article" id="article"></textarea>` 在 controller 中可以使用 `article = params[:article]` 来接收这个变量，详细文档请点击 -> [详细文档](http://apidock.com/rails/ActionView/Helpers/FormTagHelper/text_area_tag)
   注意: 如果要使用 :size  等可选参数，`text_area_tag` 的第二个参数必须要输入，默认可以设置为 `nil`。

两种使用格式：
1.ext_field_tag
- `<%= text_field_tag('name', nil, :placeholder => "haha") %>`
- `<%= text_field_tag 'name', nil, placeholder:  "haha"  %>`  

2.text_area_tag
- `<%= text_area_tag('article', nil, :size => "5x5") %>`
- `<%= text_area_tag 'article', nil, size: "5x5" %>`
