### ISSUE TITLE
为什么Controller 中的 index 和 show 等方法没有 redirect_to 也会自动寻找响应到 view

### ISSUE THREAD

**Issue by shaojunda** [quanzhanying/fullstack-course#12]

**Comment by nfreeness** [comment]
因为index和show有自己的view，在上面执行指令后它会回到本身的view（当然也可以自定义指向），而update和destroy没有自己的view，所以执行之后要重新定向到你想要的view

**Comment by shaojunda** [comment]
@nfreeness 谢谢。

**Comment by shaojunda** [comment]
controller 中的方法，比如 show 方法，结束后会自动寻找同名的页面，比如 show 方法结束后默认会去寻找 show.html.erb，但是也可以通过 redirect_to 指定。
