### ISSUE TITLE
“” 和''的区别和各自用法是什么？

### ISSUE THREAD

**Issue by rebecca9201** [quanzhanying/fullstack-course#15]

**Comment by nfreeness** [comment]
之前助教解答说没有区别，比如gem "devise"和gem 'devise'是一样的。

**Comment by rebecca9201** [comment]
单引号和双引号都可以用来创建字符串。
大部分情况下输出结果是一致的，但是使用这两种方式创建特殊字符串时，会有差别。
 双引号创建字符串：会对转义字符和特殊字符进行替换，即内容会被转译;
 单引号创建字符串：不进行替换，即内容不会被转译。
 测试代码如下:
![image](https://cloud.githubusercontent.com/assets/20454220/17181401/98e68e90-5452-11e6-9fbd-8b408fa97f5c.png)
