### ISSUE TITLE
各种括号的规则及其用法？

### ISSUE THREAD

**Issue by nfreeness** [quanzhanying/fullstack-course#16]
（ ）、 ［ ］ 、｛ ｝、< > 、  | |  这些不同的括号使用规则是什么？
比如很多时候一组（）里面可以再包含一组（），而有的（）里包含的却是｛｝。

**Comment by liusining** [comment]
http://sining-liu-blog.logdown.com/posts/775104-the-use-of-brackets

**Comment by gbt1988** [comment]
## 1.圆括号`( )`用来组合逻辑和数学表达式,也用来对功能添加说明.例如

Parentheses () are for grouping logical or mathematical expressions and grouping arguments to a function call, e.g.:

```
a = 2 * (3 + 4)  #一个算术式
b = (x==y) || (m==n) #一个逻辑表达式 
Hash.new.send('[]=', :a, :b)# 在send method中调用将:a,:b的hash作为参数
```

## 2.大括号{},用于散列和块中

Curly Braces `{}` are used for hash literals and blocks, e.g.:

> hash是一种關連陣列 (associative array), 不同於用數字序列的索引號碼提取內容，而是用一個 鍵 (key) （編註：可用任何物件當做 Key，但通常是 Symbol、String 字串或 Fixnum 整數）。這種陣列一般稱為雜湊 (hash) 或字典 (dictionary).

```
h = {1=>2, 2=>3} #这里用在散列中
h.each {|k,v| puts k+v} #这里的大括号,用在block中.
```

> block的概念比较复杂.block依赖method发生作用.这个概念,有兴趣的朋友可以看下这篇[有意思的文章](http://tao.logdown.com/posts/166766-vernacular-ruby-block)

## 3.方括号[]用来表示数组,数组角标和切片.并且从散列中获取数据

Square Brackets [] are used for array literals, array indexing and slicing, and fetching from a hash, e.g.:

arr = [1, 2, 3]  一个数组
two = arr[1]  数组1的位置是"2"
three = h[2]  key"2",的值(value)为"3"

> 在阵列中,排在第一个位置的项目,角标是0(而不是1)

fruits = ["apple", "banana", "cherry"]
| array        | nil        | "apple"| "banana"| "cherry"|  nil        |
| --------   | -----:  | :----:    | :----:       | :----:     |:-------:|
| index       | 0          |1           |2                |3             |4           |

```
`2.3.1 :018 >
puts fruits[0] =>apple
puts fruits[1]  =>banana
puts fruits[2] =>cherry
```

> 还可以倒着来.最后一位是-1,倒数第二个对应的-2,以此类推.

```
`2.3.1 :018 > puts fruits[-1]
cherry
 => nil
2.3.1 :019 > puts fruits[-2]
banana
 => nil
2.3.1 :020 > puts fruits[-3]
apple
```

> 下面是一段切片,切片就是截取数组的某一部分,fruits[0...1]就是把fruits数组里面角标从0到1的元素找出来.(分别对应数组的第1\2位)

```
2.3.1 :026 > fruits[0..1]
 => ["apple", "banana"]
```

## 4.有种情况比较让人困惑,散列也可以用来做一个method的说明,而无需大括号或小括号,因为它是最后一个声明.另外,散列也可以用方括号来产生,去建立一个包括包含散列的的单项目数组.

To confuse the matter, hash literals can also be used in-place as an argument to a method call without needing the curly braces or parentheses as long as it is the last argument (thanks samuil). Additionally, hash literals can be used in-place in square brackets to create a single-item array containing the hash:

```
2.3.1 :024 > puts 1=>2, 3=>4
{1=>2, 3=>4}
 => nil
2.3.1 :025 > [5=>6, 7=>8]
 => [{5=>6, 7=>8}]
2.3.1 :026 >
```

When in doubt, always use parentheses to group items and wrap your hashes in curly braces.

当可能引起歧义时,用小括号括包括条目,用大括号包住散列

## 5."xxxx.each.do | f  |" 是迭代器," ||"称为逻辑"或"运算符(另外两个是 &&(与)、！(非))

"||" 或运算符。如果两个操作数中有任意一个非零，则条件为真。(a || b) 为真。
"|     |"这个符号的概念,用在迭代器中的概念,就叫做集合了.each 迭代器返回数组或哈希的所有元素。
each 迭代器返回数组或哈希的所有元素。

[语法](http://www.runoob.com/ruby/ruby-iterators.html)

```
collection.each do |variable|
   code
end
```

## 6."<"在运算中做"小于",在=>用来指定散列值(value)和键(key)的对应关系.{key=>value]},也可表示为h[key]=value;"<>"尖括号在html中各种标签会运用到,同时在其他语言中也会用到.<%  %>执行;<%= %>打印-----更多用法待(补充)

参考:[0](http://www.runoob.com/ruby/ruby-array.html)[1](http://liuzxc.github.io/articles/ruby-block-proc-lambdas/)[2](http://tao.logdown.com/posts/166766-vernacular-ruby-block)[3](http://rubyer.me/blog/917/)[4](http://guides.ruby.tw/ruby/arrays.html)[5](http://docs.ruby-lang.org/en/2.0.0/Hash.html)[6](http://stackoverflow.com/questions/3323148/braces-brackets-parentheses-curlies-in-ruby-rails)[7](https://ruby-china.org/topics/10414)[8](http://www.cnblogs.com/Goden/p/3795162.html)[9](http://developer.51cto.com/art/200912/169320.htm)[10](http://www.bkjia.com/ruby/1136790.html)
