### ISSUE TITLE
如何修改last update的时间为北京时间？

### ISSUE THREAD

**Issue by nfreeness** [quanzhanying/fullstack-course#18]
在job的栏位采用<%= job.updated_at %>来显示最新更新时间，但是显示的结果是2016-07-27 03:45:19 UTC这样的时间，如何将它显示成北京时间？

**Comment by chpwang** [comment]
Google 关键词：rails timezone application.rb

**Comment by nfreeness** [comment]
在application.rb中添加以下两条配置, 
config.time_zone = 'Beijing'
config.active_record.default_timezone = :local
