### ISSUE TITLE
<% xxx do |aaa, bbb| %>中的aaa和bbb怎么分别使用

### ISSUE THREAD

**Issue by liusining** [quanzhanying/fullstack-course#19]
<img width="650" alt="2016-07-27 12 50 41" src="https://cloud.githubusercontent.com/assets/20436146/17164281/5f23a0d4-53f9-11e6-9d3d-7e7e9cf118f2.png">

**在_flashes.html.erb中，为什么我写flash[:alert] = "You're not admin!",只会在value的位置贴出，而不会赋值给key？**
如果我想多贴出一些东西，要怎么才能让新增的｜ccc，ddd｜找到自己应该拿到的数据？比如：

<img width="703" alt="2016-07-27 12 49 53" src="https://cloud.githubusercontent.com/assets/20436146/17164435/bf0f1f2c-53fa-11e6-8d60-fe134f6f3914.png">

**Comment by chpwang** [comment]
Google 搜索关键词： ruby hash key value

**Comment by nieyicheng** [comment]
散列的循环

使用each方法，我们可以遍历散列里的所有元素，逐个取出其元素的键和对应的值。循环数组时是按索引顺序遍历元素，循环散列时候按照键值组合遍历元素。

散列的each语法如下

散列.each do |键变量, 值变量|
希望循环的处理
end

事例

address = {name: "弋程", pinyin: "yicheng"}
=> {:name=>"弋程", :pinyin=>"yicheng"}
address.each do |key, value|
    puts "#{key}: #{value}"
end
name: 弋程
pinyin: yicheng
=> {:name=>"弋程", :pinying=>"yicheng"}
显而易见，程序循环执行了输出散列address的键和值的puts方法。
