### ISSUE TITLE
我想通过在migrate中手动加入一行语句来制作一个栏位，为什么不行？

### ISSUE THREAD

**Issue by liusining** [quanzhanying/fullstack-course#20]
<img width="528" alt="2016-07-27 13 10 05" src="https://cloud.githubusercontent.com/assets/20436146/17164526/9b7ed56a-53fb-11e6-8438-4698ca36ac56.png">

我通过编辑器在migrate中加了一行 `t.text :other`或者`add_column :jobs, :haha, :boolean, default: true`，然后rake db:migrate，就什么都没有发生。**只能通过rails g migration XXX 来新增栏位么？**

<img width="649" alt="2016-07-27 13 08 34" src="https://cloud.githubusercontent.com/assets/20436146/17164584/417245c4-53fc-11e6-9f00-3980b182d6a8.png">

**Comment by nfreeness** [comment]
新增栏位的流程是rails g migration xxx，在db中新增的文件增加栏位，最后rake db:migrate
http://nfreeness.logdown.com/posts/2016/07/27/add-data-fields-to-the-process
