### ISSUE TITLE
冒号是什么意思？

### ISSUE THREAD

**Issue by linzhewei** [quanzhanying/fullstack-course#27]
%= link_to("Edit",edit_admin_job_path(job),class:"btn btn-primary") %>
class:"btn btn-primary"中的冒号是什么意思？执行？赋值？

**Comment by linzhewei** [comment]
这段内容会展开成`<a href="edit_admin_job_path" class="btn btn-primary">Edit</a>`
例如：
`link_to "Profile", profile_path(@profile)`
=>`<a href="/profiles/1">Profile</a>`

`link_to "Profiles", profiles_path`
=> `<a href="/profiles">Profiles</a>`

**Comment by rebecca9201** [comment]
这段代码应该如下：
` <%= link_to("Add a job", new_admin_job_path, :class => "btn btn-default") %> `

**Comment by shaojunda** [comment]
`class:"btn ban-primary"` 的意思是 将 a 标签的 class 属性的值设置为 "bin ban-primary"。
