### ISSUE TITLE
关于数据验证

### ISSUE THREAD

**Issue by shaojunda** [quanzhanying/fullstack-course#28]
我的代码放在  [here](https://gist.github.com/shaojunda/11a601f212368bac832eb6f45234397a)  

在做 job-listing 项目，发现当管理员在修改或者新增 job 记录的时候，最低工资和最高工资的数据验证信息不正确。我是这样操作的，我在 Wage lower bound 这个输入框输入字母 a 点击 submit 按钮，提示信息如图。

如图：

![screen shot 2016-07-27 at 3 13 20 pm](https://cloud.githubusercontent.com/assets/5165454/17167129/f2d782aa-540d-11e6-966d-f9f94ceb9d21.png)

提示信息是 Wage lower bound 这一栏 can't be blank，但是 Wage lower bound 并不是为空。

如何修改默认的错误提示信息？

**Comment by chpwang** [comment]
google 搜索 rails validates error

**Comment by chpwang** [comment]
我这边显示，validates 检测有顺序，如果 presence 放在前，就先报 presence 的错。比如你把 presence 放在前，然后填入不是数字的数据，它会报错，错误内容是 presence 的错（最前面的那个检测的错误讯息）。

**Comment by chpwang** [comment]
我的暂时的解决方案是只做 numericality 的检测，不做 presence 的

**Comment by shaojunda** [comment]
将验证方法中的 `numericality: {greater_than: 0}`  放到  `presence: true` 前面之后就会出现正确的提示信息 is not a number。 这可证明验证方法是按顺序起作用的。

自定义错误提示信息可通过使用 `:message` 来实现，例子：
`validates :wage_lower_bound, presence: {message: "%{attribute}不能为空"}` 
可用参数有 `%{value}, %{attribute}, and %{model}`
[文档地址](http://guides.rubyonrails.org/active_record_validations.html#common-validation-options)
