### ISSUE TITLE
-u , -b 是什么意思？

### ISSUE THREAD

**Issue by panxiubin** [quanzhanying/fullstack-course#29]
比如： git push －u origin master 的 －u
git checkout －b ch01 的 －b

**Comment by nfreeness** [comment]
－u是预设以后默认把本地的master分支push到github的origin分支
－b是新建一个分支，git chekout －b ch01的意思是在拷贝当前分支的状态并建立一个ch01的分支，同时从当前的分支checkout到刚刚建立好的ch01分支

**Comment by shaojunda** [comment]
`git push -u origin master` -u 的含义可以通过执行 `git push -h` 来查看。

> set upstream for git pull/status

可以理解为，告诉 git 将本地项目与远端的 repo 进行关联，关联之后你只需要执行 `git push` git 就知道将新的内容推送到哪个 repo 中了。 

参考： [what does git push u mean](http://stackoverflow.com/questions/5561295/what-does-git-push-u-mean)

`git checkout -b ch01` 其实做了两个动作，先创建了一个分支，然后再切换到新建的分支上。可以理解为执行了两条命令，分别是 `git branch ch01` 和 `git checkout ch01`， `git branch ch01` 命令是用来创建名字为 ch01 的分支，`git checkout` 用来切换到 ch01 分支。
