### ISSUE TITLE
请老师简单讲一下https的安全原理

### ISSUE THREAD

**Issue by nfreeness** [quanzhanying/fullstack-course#31]
比如刚刚在访问https://xin.ontrackapp.com/的时候，chrome浏览器会报错说这是个不安全网址，地址栏的https标签是红色的状态，需要自己进一步点击才能打开浏览。

但是过一会在chrome里面重新刷新https://xin.ontrackapp.com/的时候，https的标签又变成安全的绿色状态了。

**Comment by geophyli** [comment]
红色状态应该是因为没有找到安全证书或者安全证书已经过期了，变绿应该是安全证书更新了。https://www.zhihu.com/question/19577317

**Comment by nfreeness** [comment]
http是明文传送内容，https是加密传输内容，有些网站在登陆页用https（保护密码），有些网站全程使用https。
