### ISSUE TITLE
求一个快捷键

### ISSUE THREAD

**Issue by gbt1988** [quanzhanying/fullstack-course#33]
现在我正在在finder里，practice/0728/job文件夹里。有没有快捷键可以直接打开item 并且打开的item正好定位在当前目录。

**Comment by shaojunda** [comment]
可以去 App Store 下载 Go2Shell

**Comment by chpwang** [comment]
补充一个可能有用的教程（Mac必备神器之Go2Shell以及使用技巧）：http://www.jianshu.com/p/88c6e68645c4
