### ISSUE TITLE
请详细讲一下什么时候新建branch，以及什么节点进行commit？

### ISSUE THREAD

**Issue by DJ-MinorG** [quanzhanying/fullstack-course#40]
比如CRUD 全部完成commit可以吗？

**Comment by chpwang** [comment]
可以。commit 你可以理解为保存，一般来说会在没完成一个任务的时候保存。这个任务的大小看个人习惯和方法论，你可以完成小任务就 commit，也可以完成很大的任务之后才 commit 。 关于分支，你可以参考[这里](http://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000/0013743862006503a1c5bf5a783434581661a3cc2084efa000)
