### ISSUE TITLE
什么样的程式要写进helper

### ISSUE THREAD

**Issue by DJ-MinorG** [quanzhanying/fullstack-course#43]
和 _form.html.erb 有什么区别？

**Comment by gbt1988** [comment]
会被views中格式为.html.erb引用的函数需要写进helper。partial也会被引用，但他们的用途不同。helper用来整理rb程式，而partial用来整理html内的大段、共用的元素，对页面进行整理简化。

## 基本认识
- patial 是views文件夹中下划线开头文件,如_form.html.erb它可以被同目录下的文件调用(render).调用时不需要加下划线。

例子:之前的中级课程中.app/views/groups/new.html.erb文件中通过`render:form`调用同目录下的_form这个partial。

```
<div class="col-md-4 col-md-offset-4">
    <h2>新增討論版</h2>
    <hr>
    <%= render "form" %>
</div>
```
- helper是个函数，它是.rb格式的文件。helper被views中的.html.erb文件调用,产生一段html元素代码,最终集成在html页面中。在创建Controller的時，Rails会自动生成一個同名的Helper文件，按照惯例**该Controller下的Template**所用的Helper，就放在该文件下。如果是全站使用的Helper，則會放在app/helpers/application_helper_rb.除了使用Rails內建的Helper，我们也可以自己定义Helper，只需要将方法放在在app/helpers/目录下任一個文件即可。
- 一般情况下partial用来简化页面，helper在template中用来被.html.erb调用产生html。
- 另外:redirect_to和render有什么区别呢?redirect_to会结束当前响应，向浏览器发送重定向状态,请求一个新的url ;而render调用一个**action对应的html.erb**(渲染用户指定的模板)，并向浏览器发送一个包含调用信息的完整响应。

## 进一步认识
- helper是一个概念,我们实际使用的是helper method.rails源码中内建了很多helpermethod 如 form_for,link_to   [这里forkrails源码◀️](https://github.com/no4long/rails)   [这里是常见helper◀️](https://rocodev.gitbooks.io/rails-102/content/chapter1-mvc/v/essential-helpers.html)
- rails通过template模板,建立html.erb文件以产生html页面,views中的文件其实就是template模板产生的.而helper就是给template用的(不仅限于html.erb,template还可以产生其他格式的文件)。另外,route也可以产生helper method。

> 参考
> [helper介绍一](https://ihower.tw/rails4/actionview-helpers.html)
> [helper介绍二](http://motion-express.com/blog/20141025-rails-helper)
> [如何写helper的用法](http://blog.xdite.net/posts/2012/01/16/how-to-design-helper-3)
> [heleper全局引用](http://stackoverflow.com/questions/6550103/in-which-folder-should-i-put-global-shared-partial-templates)
> [路由介绍一](http://guides.ruby-china.org/routing.html)
> [路由介绍二](https://ihower.tw/rails4/routing.html)
> [helper&controller](http://blog.csdn.net/e_online/article/details/4008306)
> [关于template](https://ihower.tw/rails4/actionview.html)
> [render和redirect](http://bellstar.iteye.com/blog/426628)
