### ISSUE TITLE
layout 和css的区别？不都是用来给网页穿衣服的吗？

### ISSUE THREAD

**Issue by DJ-MinorG** [quanzhanying/fullstack-course#44]

**Comment by shaojunda** [comment]
我觉得 layout 是一个架子，它包含了 css 和  js。而且对某一个 Controller 应用了某个 layout 之后，由这个 Controller render 的所有 view 就都会换成新的 layout 。可以试着给 job 也将上 admin  的 layout 看一下效果。

**Comment by DJ-MinorG** [comment]
我可以理解为layout给contoller下面所有网页穿衣服，而css只给某一个网页穿衣服吗？
谢谢你的回答。

**Comment by chenyunli6** [comment]
layout给引用了layout的controller下的所有网页穿衣服，css给引用了这个css的所有网页穿衣服

在 2016-07-29 14:43:45，"cuckoo8695" notifications@github.com 写道：

我可以理解为layout给contoller下面所有网页穿衣服，而css只给某一个网页穿衣服吗？
谢谢你的回答。

**Comment by shaojunda** [comment]
@cuckoo8695 首先，整体来看可以把 layout 理解为一个模版，layout 不只是用来给页面“穿衣服”的，还会有动作（js），但如果单从“衣服”的角度来看，我觉得可以把 layout 理解为一个衣柜，这个衣柜里可以有很多的 css。在使用的时候，只要把应用该 layout 的页面所要用的 css 都放在这个 layout 里就可以了。单一的 css 会对引用它的页面起作用。从“穿衣服”的角度来看， layout 就是帮你把所要用的 css 都加载好了。

**Comment by shaojunda** [comment]
@cuckoo8695 从使用上来看，在 job-listing 项目中，求职者所有页面的默认模版是 application.html.erb 我们想为管理员设计不一样的页面，但如果使用新的 layout ，就需要在 application.html.erb 里控制哪些是要给求职者展示，哪些是要给管理员展示，这样会很麻烦，代码也会比较乱。当时当求职者和管理员分别使用不同的 layout 的时候，分别设计自己的页面就可以了。直观一点来理解就是，我们要为管理员加上  sidebar， 但是求职者没有 sidebar 这个sidebar 要在管理员使用的所有页面都出现，所以我们使用了新的 layout，这样就达到了让求职者的页面就没有 sidebar，而管理员的页面有 sidebar 的目的。
