### ISSUE TITLE
为什么命名为 _navbar.html.erb而不是 navbar.html.erb？

### ISSUE THREAD

**Issue by DJ-MinorG** [quanzhanying/fullstack-course#45]

**Comment by shaojunda** [comment]
这是一个命名规范，为了将 partial 与普通的 view 区分开来，因为在默认情况下 action 会 render 同名的 view，比如 controller 中的 index 默认会去 render index.html.erb。

参考 [Action View Partials](http://api.rubyonrails.org/classes/ActionView/PartialRenderer.html)

**Comment by DJ-MinorG** [comment]
我试了一下改成navbar.html.erb, 确实会报错。谢谢

**Comment by chpwang** [comment]
@cuckoo8695 

"We don’t have to map any of these things together if we use conventions. That’s why sometimes people say that Rails follows "convention over configuration. 
If we can follow some intelligent defaults or conventions, then we can avoid configuration."
