### ISSUE TITLE
添加association后的3个问题

### ISSUE THREAD

**Issue by DJ-MinorG** [quanzhanying/fullstack-course#47]
1在group和user关联之后我好像并没有给group 的user_id 赋值，是通过哪部赋值的？
2@group.user=current_user 是把current_user 所有信息（email, passward..)全部给了 @group.user? 
3@group.user 是什么意思？

**Comment by chpwang** [comment]
我已经在 [这里](https://github.com/xingrowth/fullstack-course/issues/48) 回答了。如果还有什么不明白，明早来问我（一组第二个使用竖屏显示器的人）

**Comment by DJ-MinorG** [comment]
我自己回答一下第2和第3个问题，错了请指出：
@group.user=current_user 并没有把current_user 所有信息如email等给@group，而只是把current user 的:user_id 给了group， group可以通过这个:user_id 去找user的各种信息比如<%= group.user.email %>

所以感觉@group.user有点像@group.user(params[:user_id])的简写？？？

**Comment by DJ-MinorG** [comment]
1. group.user 其实是在@group.user=current_user的时候赋值， 其实为@group.user_id=current_user.id。另外@user.groups 其实同时被赋值
2. 看上条comment
3. @group.user 实际是@group.user_id
