### ISSUE TITLE
why "delete" not "destroy" in views?

### ISSUE THREAD

**Issue by DJ-MinorG** [quanzhanying/fullstack-course#5]
我们在app/views/groups/index.htm.erb 中写method＝>:delete 为什么是delete不是destroy？写delete可以调用到destroy action吗？

<%= link_to("Destroy", admin_job_path(job), :**method => :delete**, :data => { :confirm => "Are you sure?" }) %>

**Comment by geophyli** [comment]
可以看一下这个API文档，methods部分http://api.rubyonrails.org/classes/ActionController/Parameters.html

**Comment by DJ-MinorG** [comment]
记住就好。。
