### ISSUE TITLE
老师讲一下各种注解吧。

### ISSUE THREAD

**Issue by chenyunli6** [quanzhanying/fullstack-course#51]
比如，怎么在html中注解<% %>,还有各种注释，尤其是多行注释的快捷键

**Comment by geophyli** [comment]
1，在%后面加一个#号就可以    <%# stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
2，多行注释可以使用快捷键command + /  来完成

**Comment by Liber17321** [comment]
在Atom中按 <kbd>Cmd</kbd> + <kbd>/</kbd>这个快捷键，可以注释光标所在的语句。想要多行注释，就选中那些行，再按这个快捷键就可以了。

但是在.erb文件中，上述注释方法对ruby代码所在的行是无效的。  
对于一行ruby代码要用下面这种方式来注释：

``` erb
<%# your_ruby_code %>
```

对于多行ruby代码要用下面这种方式：

``` erb
<% if false %>
code to comment
<% end %>
```

具体可以参考[这里](http://stackoverflow.com/questions/3127644/block-comments-in-html-erb-templates-in-rails)
