### ISSUE TITLE
如何使用 API 文档

### ISSUE THREAD

**Issue by shaojunda** [quanzhanying/fullstack-course#52]
老师，可以讲一下如何使用 API 查资料吗？比如我想查 scope 的用法，如果去查 API 的话，会感觉很懵不知道该怎么看，看 scope 的 guide 就清晰很多。

[api-scope](http://api.rubyonrails.org/classes/ActiveRecord/Scoping/Named/ClassMethods.html)

[guide-scope](http://guides.rubyonrails.org/active_record_querying.html#scopes)

**Comment by xdite** [comment]
看 guides 找到你要的東西就好了。guides 是給人「用」的。
API 文檔那邊主要是要給想給人，深層研究的。。。。
