### ISSUE TITLE
关于任务地图和用户故事

### ISSUE THREAD

**Issue by shaojunda** [quanzhanying/fullstack-course#53]
请问
- 任务地图和用户故事的制作有先后顺序吗？感觉制作了用户故事之后，似乎没必要在做任务地图了。
- 能否带领我们强化一下对这两个工具的使用？

**Comment by xdite** [comment]
這個呢。週三教。

任務地圖呢 主要是砍大方向梳理第一層的。用戶故事是往下精梳的。
