### ISSUE TITLE
controller中的@job和view里的@job是一个意思么？

### ISSUE THREAD

**Issue by linzhewei** [quanzhanying/fullstack-course#56]

**Comment by shaojunda** [comment]
controller 中的 @job 表示声明一个叫 job 的实例变量，view 中的 @job 表示在 view 中使用 @job 变量。

**Comment by shaojunda** [comment]
controller 中的 @job 表示声明一个叫 job 的实例变量，view 中的 @job 表示在 view 中使用 @job 变量。

**Comment by shaojunda** [comment]
controller 中的 @job 表示声明一个叫 job 的实例变量，view 中的 @job 表示在 view 中使用 @job 变量。

**Comment by shaojunda** [comment]
controller 中的 @job 表示声明一个叫 job 的实例变量，view 中的 @job 表示在 view 中使用 @job 变量。

**Comment by shaojunda** [comment]
controller 中的 @job 表示声明一个叫 job 的实例变量，view 中的 @job 表示在 view 中使用 @job 变量。

**Comment by shaojunda** [comment]
controller 中的 @job 表示声明一个叫 job 的实例变量，view 中的 @job 表示在 view 中使用 @job 变量。

**Comment by shaojunda** [comment]
controller 中的 @job 表示声明一个叫 job 的实例变量，view 中的 @job 表示在 view 中使用 @job 变量。

**Comment by shaojunda** [comment]
参考：[variables](http://stackoverflow.com/questions/14319347/variables-in-ruby-on-rails)

**Comment by kurotyan514** [comment]
這邊你可能先要理解什麼是instance variable (@job)
你要在action裡定義變數為instance variable
之後再view裡面才可以使用這個變數，如果使用local variable的話view是抓不到的
所以他們是同一個是對的，但還是要去理解為什麼他們是一樣的
