### ISSUE TITLE
概念性的问题，有很多名词和概念需要老师耐心的解释。谢谢老师！

### ISSUE THREAD

**Issue by chenyunli6** [quanzhanying/fullstack-course#57]
1.对象、类 以及 面向对象
2.参数 以及 变量 
3.赋值 以及  引用
4.model和数据库表的关系
5.方法以及调用方法
6.私有方法以及私有属性

**Comment by geophyli** [comment]
类是一类具有相同属性和方法的抽象集合，类的实例化对象叫做对象。比如，mac电脑是一个类，mac电脑的具体化对象，mac Air和mac Pro就是对象。mac电脑被具体化为mac pro的过程就叫实例化，mac pro就是对象，mac电脑就是类。面向对象是一种编程思想，和面向过程相对，面向对象就是在将需要解决的问题与现实情景对应，设计出易于理解的软件系统的思想，将具有相同行为和属性的归纳为类，使用时再根据具体情况将类实例化为对象进行处理或调用方法。在Ruby中，所有的内容都是对象，它们都具有各自的属性和方法。

**Comment by geophyli** [comment]
参数是方法调用时传递给方法的数据，例如login(user user) 就是调用登录方法的时候需要传递user也就是用户信息才可以实施登录行为。 而在Ruby中，我们可以直接login(user)  也是和上面一样的意思，因为Ruby不需要声明对象是属于哪个类的实例化对象。变量是在Ruby的方法中可以被赋值改变的对象。在Ruby 中，变量是不需要显式声明属于哪个类的。

**Comment by ghost** [comment]
# 5 Ruby 方法和使用

Ruby 方法与其他编程语言中的函数类似，用于实现一个功能。

## 命名规则

方法名应以小写字母开头。如果您以大写字母作为方法名的开头，Ruby 可能会把它当作常量，从而导致不正确地解析调用。

方法应在调用之前定义，否则 Ruby 会产生未定义的方法调用异常。

## 语法

```
def method_name [( [arg [= default]]...[, * arg [, &expr ]])]
   expressions
end
```

## 方法定义

所以，您可以定义一个简单的方法，如下所示：

```
def method_name 
   expressions
end
```

您可以定义一个接受参数的方法，如下所示：

```
def method_name (var1, var2)
   expressions
end
```

您可以为参数设置默认值，如果方法调用时未传递必需的参数则使用默认值：

```
def method_name (var1=value1, var2=value2)
   expressions
end
```

## 方法调用

当您要调用方法时，只需要使用方法名即可，如下所示：

```
method_name
```

但是，当您调用带参数的方法时，您在写方法名时还要带上参数，例如：

```
method_name 25, 30
```

使用带参数方法最大的缺点是调用方法时需要记住参数个数。例如，如果您向一个接受三个参数的方法只传递了两个参数，Ruby 会显示错误。

## 示例

如下代码使用默认参数值：

```
#!/usr/bin/ruby

-- coding: UTF-8 --

def test(a1="Ruby", a2="Perl")

puts "编程语言为 #a1"

puts "编程语言为 #a2"

end

test
```

输出结果：

```
编程语言为 Ruby

编程语言为 Perl
```

如下代码覆盖默认参数值：

```
#!/usr/bin/ruby

# -*- coding: UTF-8 -*-

def test(a1="Ruby", a2="Perl")
   puts "编程语言为 #{a1}"
   puts "编程语言为 #{a2}"
end
test "C", "C++"
```

输出结果：

```
编程语言为 C

编程语言为 C++
```

## 参考

[Ruby 方法| 菜鸟教程](http://www.runoob.com/ruby/ruby-variable.html)

**Comment by ghost** [comment]
# 4. Model 和 Datebase

Active Record 是 MVC 中的 M（模型），处理数据和业务逻辑。Active Record 负责创建和使用需要持久存入数据库中的数据。

Active Record 涉及:
    • 表格(创建、增加栏位、修改属性等)
        • 迁移
    • 表格关系(一对一, 一对多, 多对多)
    • CRUD(Create, Read, Update, Delete)
    • 数据验证(非空、唯一等)

Active Record 是 MVC 中的 M（模型）:

![](https://dylanninin.com/assets/images/2013/rails/rails_mvc_m.png)

## 表格

创建。跑指令`rails g model job title:string description:text`，会生成model的表格。

app/models/job.rb

```
 class  Job < ApplicationRecord 
 end
```

## 迁移

迁移。跑指令`rake db:migrate`，将表格迁移到数据库。迁移的代码存储在特定的文件中，通过 rake 调用，可以用在 Active Record 支持的所有数据库上。下面这个迁移会新建job model的数据表：

db/migrate/20160802104658_create_jobs.rb

```
class CreateJobs < ActiveRecord::Migration[5.0]
  def change
    create_table :jobs do |t|
      t.string :title
      t.text :description

      t.timestamps
    end
  end
end
```

Rails 会跟踪哪些迁移已经应用到数据库中，还提供了回滚功能。创建数据表要执行 rake db:migrate 命令；回滚操作要执行 rake db:rollback 命令。

## 表格关系

 一对多。一个职位(job)可以收到多份(resume)简历。
app/models/resume.rb

```
class Resume < ApplicationRecord
    belongs_to :job
end
```

app/models/job.rb

```
class Job < ApplicationRecord
    has_many :resumes
end
```

## CRUD 

`save` 如果记录被保存，save 返回真；否则返回nil。

app/controllers/jobs_controller.rb

```
def create @job = Job.new(job_params)
      if @job.save 
          redirect_to jobs_path 
else 
      render :new end
end
```

## 数据验证 

在存入数据库之前，Active Record 还可以验证模型。模型验证有很多方法，可以检查属性值是否不为空、是否是唯一的，或者没有在数据库中出现过，等等。  如下代码可以实现，title栏位不能为空。

app/models/job.rb

```
class Job < ApplicationRecord   validates :title, presence: true
  has_many :resumes
end
```

## 参考
1. [Active Record 基础 - RailsGuides](http://guides.ruby-china.org/active_record_basics.html)
2. [Active Record in Rails 4 - dylanninin
   ](https://dylanninin.com/blog/2013/11/25/rails4_ar.html)

**Comment by ghost** [comment]
# 6 Ruby 私有方法

私有方法 仅对象内可用。

## private含义

C++, “private” 意为 “private to this class”, 但是Ruby中意为 “private to this instance”.
意思是：C++中，对于类A，只要能访问类A，就能访问A的对象的private方法。
Ruby中，却不行：你只能在你本对象的实例中访问本对象的private方法。
因为Ruby的原则是“private意为你不能指定方法接收者”，接收者只能是self，且self必须省略！
所以Ruby中子类可以访问父类的private方法。

## private方法定义

private下面的方法 全部都被设为private。

```
class Example
    def methodA
    end

    private

    def methodP
    end
  end
```

只定义methodP为private。

```
  class Example
    def methodA
    end

    def methodP
    end

    private :methodP
  end
```

## 示例

Ruby中private指的是”你不能明确接收者”。

```
  class AccessPrivate
    def a
    end
    private :a # a 是一个私有方法

    def accessing_private
      a              # 可以！
      self.a         # 不可以！private方法不能用明确的接收者来调用，即便这个接收者是”self”
      other_object.a # 不可以！ private方法, 不能被其他对象访问。   end
  end
```

## 参考

[Ruby Programming/Syntax/Classes  - wikibooks](https://en.wikibooks.org/wiki/Ruby_Programming/Syntax/Classes#Declaring_Visibility)
[Ruby Tutorial: Scope Ruby Scope - newcircle](https://newcircle.com/bookshelf/ruby_tutorial/scope)
[Ruby中访问控制符public，private，protected区别总结 - Ruby迷](http://rubyer.me/blog/667/)

**Comment by ghost** [comment]
# 1 Ruby 面向对象、类和对象

## Ruby 面向对象

Ruby 是纯面向对象的语言，Ruby 中的一切都是以对象的形式出现。Ruby 中的每个值都是一个对象，即使是最原始的东西：字符串、数字，甚至连 true 和 false 都是对象。类本身也是一个对象，是 Class 类的一个实例。
类用于指定对象的形式，它结合了数据表示法和方法，把数据整理成一个整齐的包。类中的数据和方法被称为类的成员。

## Ruby 类定义

当您定义一个类时，您实际是定义了一个数据类型的蓝图。这实际上并没有定义任何的数据，而是定义了类的名称意味着什么，也就是说，定义了类的对象将由什么组成，以及在该对象上能执行什么操作。
类定义以关键字 class 开始，后跟类名称，最后以一个 end 进行分隔表示终止该类定义。例如，我们使用关键字 class 来定义 Box 类，如下所示：

```
class Box
   code
end
```

按照惯例，名称必须以大写字母开头，如果包含多个单词，每个单词首字母大写，但此间没有分隔符（例如：CamelCase）。

## 定义 Ruby 对象

类提供了对象的蓝图，所以基本上，对象是根据类进行创建的。我们使用 new 关键字声明类的对象。下面的语句声明了类 Box 的两个对象：

```
box1 = Box.new
box2 = Box.new
```

## 参考

[Ruby 面向对象 - runoob](http://www.runoob.com/ruby/ruby-object-oriented.html)

**Comment by ghost** [comment]
# 2 Ruby 变量

Ruby 有三种变量、一种常量和两个伪变量 (pseudo-variable)。变量与常量并不需要类型， 虽然无类型 (untyped) 的变量有一些缺点，但有更多优点，而且符合 Ruby 快捷易用的理念。

大部分语言中，变量都需要宣告，才能指定类型、可修改性(modifiability)（即，是不是常量）、变量作用域(scope)；因为类型不再是个问题，我们会在之后的变量名称中证实，所以Ruby 并不需要变量声明。

透过标识符 (identifier)​​ 的第一个字元，就能分辨出变量：

$ 全局变量 (global variable)
@ 实例变量 (instance variable)
[a-z] 或 _ 区域变量 (local variable)
[A-Z] 常量
例外的是 Ruby 中的两个伪变量 (pseudo-variable)：self、永远指示目前正在执行的物件；nil、这是指派予未初始化 (uninitialized) 变量的无意义值。这两个都如同区域变量，self 是由直译器维护的全域变量，而 nil 则是一个常量。幸好只有两个例外，并不会造成太大困惑。

你不能为 self 或 nil 指派任何值。 main（self 的值）指的是上层 (top-level) 物件：

```
ruby> self
   main
ruby> nil
   nil
```

## 参考

[變數 Variables - Ruby 使用手冊](http://guides.ruby.tw/ruby/variables.html)
[Ruby 变量 - runoob](http://www.runoob.com/ruby/ruby-variable.html)

**Comment by ghost** [comment]
# 3 Ruby 赋值

Ruby用等于号’’=”来赋值。赋值适用于变量和对象，但由于字符串，浮点数，数值在Ruby中都属于对象，你看起来是经常在用对象给变量赋值，实际上你也能够给对象赋值。

举例

```
  myvar = 'myvar is now this string'
  var = 321
  dbconn = Mysql::new('localhost','root','password')
```

## 赋值给自己

```
x = x + 5
x = 1           #=>1
x += x        #=>2
x = x + 5    #=>2
```

## 批量赋值

```
  var1, var2, var3 = 10, 20, 30       #=> 一次性给3个变量赋值
  puts var1                                      #=>打印出来，var1 值为 10
  puts var2                                     #=>var2 为 20
  puts var3                                     #=>var3 为 30
```

## 条件赋值

```
x = x || "default" #=> ||代表逻辑或。当x为空或否时，x被赋值为”default”;
x = x && x.next_node #=> &&代表逻辑与。当x为非空或真时，x被赋值为x.next_node;
```

## 参考
1. [Assignment - Ruby Programming/Syntax/Operators](https://en.wikibooks.org/wiki/Ruby_Programming/Syntax/Operators)

**Comment by chenyunli6** [comment]
1.对象、类 以及 面向对象

对象。如果把著名的一句话拿出来，万物皆对象，我不知道大家能不能理解。

这有一只猫，我们可以说它是一个对象，这有一只狗我们也可以说它是一个对象，这有一支签字笔也是一个对象。 类，就是把这一类具有相同行为和属性的对象抽象出来，归为一类。 比如猫这个大类，包含所有的猫。之所以归位一类，是因为，这一类对象可以用共同的东西归纳出来（比如都有name，都有color，都会跑，都会喵喵的叫）。所以，如果把这些共同的行为和属性归纳起来，就可以定义一个最基本的猫。就是，它肯定不可以再是狗了。相当于做了一个猫的模板，只要由这个模板创造出来的都是猫，这个被模板创造出来的猫就是术语所说的“类的实例化”。但是，到了这一只具体的猫身上，我们都知道，它肯定和另一只猫是不一样的，也是独一无二的。我们给每一个猫不同的id，来唯一确定张三小猫不是李四小猫。猫的各大属性都有了不同。比如，张三这只猫，id＝1，name＝张三，color＝黑色； 而李四这只猫，id＝2，name＝李四，color＝白色。这就是用id，name，color这些共同的属性，创造出了不同的对象。 这就是对象和类的定义和两个之间的关系。

这种把所有物体都看成对象，抽象出属性和行为来做程序设计的方式，就叫面向对象的程序设计。把每个物体和事件都看成对象，再抽象成类，根据类，就可以new cat(),new dog(),new people()了。那么这样的话就可以在计算机世界里，用面向对象的思想去处理了，也可以扯清各对象之间的关系了。

2.参数 以及 变量

变量：
其实和数学中的变量可以同等理解。比如说x是一个变量，大家都知道的。那么写一个函数y=x+1;大家应该也知道，y是因变量，x是自变量。
数学的变量，就是这个x所代表的值是未知的，有可能是1，有可能是2，那么x=1的时候，代入式子可以得到一个结果，x=2的时候又是一个结果。

在程序中，a就可以是一个变量，job也可以是一个变量，因为它有可能代指“java工程师”这个职位，也有可能代表“ruby on rails”这个职位。所以说它是一个变量。当不同的职位代入”函数的式子“上来，会产生不同的html给用户看到。比如，薪资不同，工作职责也不同。

参数：
当把变量放在函数的式子里面用来指代某一个特定的变量时，就叫做参数。
比如 y=f(x) ，这里的x就可以叫做参数
在程序中定义edit方法是这样的

```
def edit
    @job = Job.find(params[:id])
end
```

调用edit方法，其实是edit(id) 这样的，那么，这里的id就是参数。我们可以给id这个参数传不同的值，比如id＝1来获取不同的结果。其实参数也是变量。

3.赋值 以及 引用

如果你知道变量是什么了，那么赋值就是给变量一个确定的值。

比如，a是个未知的变量，用 a=1 在程序里就可以把1这个数值赋值给a，这就说明，a里面装的是1这个数值，可以用a+1计算出等于2，因为a＝1啊
这里为啥要用变量，就是一个函数，可以用不同的数值代入，可以得到不同的结果，从而用一个函数式子来表达了所有类似的运算。
如，y=a+1,当a=1的时候，能得到2，a=2的时候能得到3.程序中也是如此。

引用：
如果把1赋值给了a，那么，a就可以被看作是1，当a作a+1=2这个运算的时候，就叫做，a引用了1这个数值。
在程序里，用也是如此。如果@job="java" 那么拿着@job这个变量就相当于拿着"java"再走，所以，就说这个过程叫做@job引用了“java”这个字符串。

4.model和数据库表的关系

看下面的表格user

| id | name | age |
| --- | --- | --- |
| 1 | Lily | 18 |
| 2 | Tom | 28 |

在数据库中，定义id,name,age三个字段形成user这个表
而在model中，也有与之对应的User这个model。用id,name,age这三个属性组成一个user对象。

在数据库中用表与表来存储数据，在ruby中用对象来易于调用数据。

比如上面的表格形式，可以清晰的看清楚数据。
而封装成对象（即model的实例），可以方便的拿到job.title,job.description

本质上都是方便管理数据。

5.方法以及调用方法

我们定义用来解决一个问题的一个特殊的代码块叫做方法。
如

```
def is_admin?
      @user = User.find(params[:id])
      if user.is_admin==true 
          flash[:notice] = "you are admin"
     else
          flash[:alert] = "you are not admin"
     end
  end
```

这就是一个方法。

而我们在别的地方需要判断这个user是不是admin的时候就可以调用这个方法。
如is_admin?(user) 其实这里只不过rails自动给你拆解好，会把user.id给传入。从而可以通过唯一的id找到一条唯一的数据，也就是唯一的对象。从而取出user.is_admin这个属性，判断它的值是什么，是true就提示，你是admin，是false就提示你不是admin

6.私有方法以及私有属性
在controller中可以看到一个private,在那个单词后面定义的变量和方法都试私有的。
私有的方法和属性，都是仅供本controller所使用的，是别的controller不可以用的。
这里就是没个方法和变量使用的范围的控制。术语叫做作用域，即作用范围。
