### ISSUE TITLE
两套job_controller做什么

### ISSUE THREAD

**Issue by chenyunli6** [quanzhanying/fullstack-course#6]
admin目录下的CRUD是管理员管理job，外面路径的那个是所有人都能观看的？那么，admin管理的不应该只是自己发布过的职位么，这里是不是还没到呢？要不感觉这两个目录分开写CRUD都是一样的。
而且做的时候，感觉这两套都是一样的，为啥还要重新开一套。

**Comment by nfreeness** [comment]
用namespce命名不同的前缀，然后区分不同用户的权限，比如观众权限和管理员权限。

**Comment by chenyunli6** [comment]
问题答案：
       jobs_controller 用来展示客户可以看到的功能
       admin/jobs_contoller 用来展示管理员可以看到的功能
       使用namespace来区分路径，不同权限不同功能路径

思考：
也就是用这个来做权限控制？
是不是有别的解决方案？

**Comment by xdite** [comment]
這是做路徑控制的。不是做權限控制的
