### ISSUE TITLE
routes中put和patch的区别？

### ISSUE THREAD

**Issue by DJ-MinorG** [quanzhanying/fullstack-course#62]

**Comment by shaojunda** [comment]
![screen shot 2016-08-04 at 1 12 18 pm](https://cloud.githubusercontent.com/assets/5165454/17391021/26d44cc2-5a45-11e6-9f31-3ad5b731a88a.png)

从这个表格来看，put 和 patch 应该没有区别，都是用来请求执行 update 操作。

参考： [routing](http://guides.rubyonrails.org/routing.html)

**Comment by ghost** [comment]
我觉得可以换一种角度去理解。PATCH/PUT是浏览器发出的动作，然后rails用来响应的动作都是photos#update。
![](http://imagizer.imageshack.us/v2/640x480q90/923/8aCfNr.jpg)

PATCH/PUT有细微的差异，但起作用的还是你的程序用来响应的动作。
![](http://imageshack.com/a/img922/5541/3nvyDD.png)

参考：[Using HTTP Methods for RESTful Services](http://www.restapitutorial.com/lessons/httpmethods.html)
