### ISSUE TITLE
老师，我对概念 return（回传）的意思很不理解。还有 一个 method 如何判断它是否带有  return 返回值的呢？以及返回值在具体中的应用是怎样的呢？

### ISSUE THREAD

**Issue by panxiubin** [quanzhanying/fullstack-course#63]

**Comment by kurotyan514** [comment]
關於return的概念是這樣的，當你呼叫一個method的時候，你除了需要這個method幫你做一些事情之外，如果你還額外需要method在做完事情之後跟你說結果的話你就需要使用return。

下面舉個例子
假設我有個method叫做addition(加法)，這個method我給他兩個值後，他會幫我把這兩個值加起來，並且回傳結果給我

```
def addition(num1 , num2)
  result = num1 + num2
end

totals = addition(2,3) #=> 5 出來的結果會是5
```

在上面的method你可能會問說可是裡面沒有寫return為什麼會有return值，那是因為ruby會自動return最後一行的結果當作回傳值，當然你也可以這樣寫

```
def addition(num1 , num2)
  result = num1 + num2
  return result
end

totals = addition(2,3) #=> 5 出來的結果會是5
```

如果要判斷某個method有沒有return值很簡單，只要去判斷那個method是不是等於nil就好

```
totals = addition(2,3) 
totals.nil?
or
if totals == nil
```

實際應用的話，其實就是上面我舉的例子，這邊再舉一個簡單的例子弄一個檢查數字是否超過100的method，另外這個method後面加上?是ruby的一種慣例，代表這是個會回傳boolean的method

```
def is_over_ hundred(number)?
  if number >100
      return true
  else
      return false
  end
end
----------------------------------
is_over_ hundred(200)? # => true
is_over_ hundred(50)? # => false
```
