### ISSUE TITLE
请问，model class 和  model instance 的methods是怎么区分的呢？它们的区别是什么呢？

### ISSUE THREAD

**Issue by panxiubin** [quanzhanying/fullstack-course#64]

**Comment by liusining** [comment]
在Ruby基础教程第四版的75页有讲解。
我总结如下：
class叫做类，instance叫做实例，因为他们在model里面，所以叫做model class 和 model instance吧。
1. 你问的他们两个的methods的区别，也就是类方法和实例方法的区别。
2. 类方法就是class能调用的方法。用书上的话说就是这个方法的接收者是一个class（类），比如我们在rails101教材中用到过这样一句话 `@group = Group.new`，其中Group就是一个class的名字，这个类调用类new这个方法，所以是Group.new。类在调用方法的时候，不仅可以用“.”英文的句号，还可以用::两个冒号。
3. 实例方法是实例在调用方法。比如我们用过`@groups.each do |group|`，do前面说的就是@groups这个实例调用each这个方法，所以这是个实例方法。

总结一下：类方法是类在调用方法，实例方法是实例在调用方法。
1. 另外，我们都可以自己定义方法，比如我们在model里面定义了admin？这个方法，然后用current_user.admin?来调用admin？这个方法。我们也可以自己定义类方法，不过我们不知道怎么从教材中找例子，可以看那本书。

如果需要看什么是类，什么是实例，可以看刚才那本书的38页。我理解实例就是一个class的真实例子，所以叫实例。
