### ISSUE TITLE
cart 和 @cart 一样吗？

### ISSUE THREAD

**Issue by DJ-MinorG** [quanzhanying/fullstack-course#67]
第二、四行中的cart等于@cart吗？

def find_cart
    cart = Cart.find_by(id: session[:cart_id])
    if cart.blank?
      cart = Cart.create
    end
    session[:cart_id] = cart.id
    return cart
  end

**Comment by DJ-MinorG** [comment]
加“@”表示可以在view里面调用，没有@表示只要在当前方法中调用。上例中变量cart不需要在view中被调用，所以没有@

**Comment by kurotyan514** [comment]
可以去參考ruby 裡的 instance variable & local variable
