### ISSUE TITLE
Cart.create 我们一般CRUD create action 中为什么不用.create 而用.new?

### ISSUE THREAD

**Issue by DJ-MinorG** [quanzhanying/fullstack-course#69]
def find_cart
    cart = Cart.find_by(id: session[:cart_id])
    if cart.blank?
      cart = Cart.create
    end
    session[:cart_id] = cart.id
    return cart
  end

**Comment by kurotyan514** [comment]
create 等於 new + save
你要用new也可以，就是要記得save
