### ISSUE TITLE
用本项目的例子解释class method 和 instance method  的区别

### ISSUE THREAD

**Issue by cndaniel** [quanzhanying/fullstack-course#79]
RT

**Comment by ray16897188** [comment]
如果只拿Model来举例子的话：
例如User.all, User.find用的就是class method，使用.all和.find的方法不需要（其实也不能）通过一个实例来调用，只能通过Model类来调用。

而@user.is_admin? @job.hide @job.publish就是instance method，它是针对具体的那个instance调用其相应的方法，返回的结果和具体的某个实例的状态有关，而和整个Model Class无关
