### ISSUE TITLE
默认的 method 

### ISSUE THREAD

**Issue by cndaniel** [quanzhanying/fullstack-course#83]
在项目中 如controller内定义 method 时候，有些是内置的如 Job.find. Job.new，有些需要自定义，哪里可以找到默认 method 的列表？哪里可以看到加入的新 gem 默认 method 的列表？

**Comment by xdite** [comment]
1. http://guides.rubyonrails.org/active_record_basics.html 這裡涵蓋了一些基本的默認 method。

其實默認 method 超級多。但是新手看 basic 就差不多了。

**Comment by xdite** [comment]
1. 新 gem 默認 method 也非常多。但是主要用法看 README 就行了。要是想更深入的看，可以看 github 上的源碼，但是一般新手不需要，腦袋看了也會比較糊塗。
